janhq/cortex

CMakeLists.txt, controllers/llamaCPP.cc, controllers/llamaCPP.h, controllers/nitro_utils.h
Add CUDA support for Nitro on amd64 - linux also
- Fix splash screen minor bug (linux will not crash on this now)
- Fix gcc issues with regex
- Add conditional params setting for ggml Cublas (cuda)
=> CUDA support for Nitro on amd64 - linux

config.json, controllers/llamaCPP.cc, controllers/llamaCPP.h
=> 37 api with llamacpp for embedding

config.json, controllers/llamaCPP.cc, controllers/llamaCPP.h, main.cc
Example curl to load model
```
curl -X POST 'http://localhost:3928/inferences/llamacpp/loadModel' \
-H 'Content-Type: application/json' \
-d '{
"llama_model_path": "/Users/alandao/Documents/codes/nitro.cpp_temp/models/llama2_7b_chat_uncensored.Q4_0.gguf",
"ctx_len": 2048,
"ngl": 100,
"embedding": true
}'
```
=> 66 feat load unload model with config at runtime

.github/workflows/build.yml
=> Correct robocopy command

LICENSE
Folks, I've submitted a PR to shift Nitro from MIT license to AGPL, as per our retreat discussion. 
* Jan wants to build Nitro as a long-term ecosystem, and will drive Nitro's development for next few years
* We want strong copyleft culture, where downstream consumers improvements are fed back into the ecosystem
* We will be investing a lot of effort into integrating TensorRT-LLM and other libraries, and want potential Jan competitors to compete with us on an even playing field
* Longer-term, we can consider a dual-licensing scheme for Nitro, to waive AGPL with a commercial license (ala MySQL)
* MongoDB
* Minio
* Increasing numbers of the r/selfhosted stack uses AGPL, and we maintain license compatibility
cc @tikikun @vuonghoainam @0xSage
=> chore: Amend license from MIT to AGPLv3

controllers/llamaCPP.cc, controllers/llamaCPP.h
- Resolve issues about weird params behaviors (due to not using get)
- Add pre_prompt features
=> Refactor params get

README.md
=> Update docs on Nitro Github

controllers/llamaCPP.cc, controllers/llamaCPP.h
credit to https://github.com/janhq/nitro/pull/97 for the unloading some changes i made.
- We will not implement a seperate function for the unload due to the fact that i might need to sync upstream from llama cpp very regularly, so direct implementation inside the background stop function will show me error everytime sync upstream
- Add stop background process 
- Background process dependent entirely on the model_load value
=> Unload model stop background

controllers/llamaCPP.cc, controllers/llamaCPP.h
- Model status
- Model information json payload
=> feat: add model status and information dump

docs/docs/examples/chatbox.md, docs/docs/features/chat.md, docs/docs/features/embed.md, docs/docs/features/prompt.md, docs/docs/new/about.md, docs/docs/new/install.md, docs/docs/new/quickstart.md, docs/docusaurus.config.js, docs/openapi/NitroAPI.yaml, docs/sidebars.js, docs/src/styles/base.scss
=> fix navigating + change api path to api-ref

.github/workflows/build.yml, .github/workflows/docs.yml
CloudFlare Pages add Preview URL to PR
=> CloudFlare Pages add Preview URL to PR

controllers/llamaCPP.cc
- Fix critical issue for n_threads (call it cpu_threads to be more declarative)
- Fix bad implementation of cont_batching feature
=> add cpu threads

docs/docs/features/chat.md, docs/docs/features/embed.md, docs/docs/new/about.md, docs/src/styles/components/base.scss, docs/src/styles/tweaks/sidebar.scss
Fix #185 
we just list down code snippet  on mobile  instead of side by side 
`Result on Mobile`
=> bug: should be responsive and stacking up on mobile

docs/docs/features/load-unload.md, docs/openapi/NitroAPI.yaml
Fix the wrong value in api ref
=> fix wrong value api ref

.github/scripts/e2e-test-linux-and-mac.sh, .github/scripts/e2e-test-windows.bat, .github/workflows/build.yml
=> Chore: Bump Nitro version

docs/docs/features/load-unload.md, docs/openapi/NitroAPI.yaml
=> add(docs): update docs for cache clean

.github/workflows/build.yml
This solves the problem:
- Nitro with CUDA on Windows have to depend on existing CUDA runtime on Windows.
- Nitro distribution should be intact, the runtime distribution should be packaged independently and install in runtime.
=> feat: CI Add packaging job for cudart runtime

.github/workflows/build.yml, .github/workflows/update-release-url.yml, README.md
Nightly build update URL in README.md file
Changes:
- Add Download Table to README.md file
- Add workflow update Nitro stable download url for new release
- Update Nightly build url will be push to README.md file
=> Nightly build update URL in README.md file

controllers/llamaCPP.cc, controllers/processManager.cc, controllers/processManager.h, main.cc
- Can destroy nitro process by sending DELETE request to processmanager example curl below
curl -X DELETE 'http://localhost:3928/processmanager/destroy'
=> feat: Add destroy feature to nitro 

docs/docs/examples/jan.md, docs/docs/examples/openai-node.md, docs/docs/examples/openai-python.md, docs/docs/examples/palchat.md, docs/docs/features/chat.md, docs/docs/features/cont-batch.md, docs/docs/features/embed.md, docs/docs/features/feat.md, docs/docs/features/load-unload.md, docs/docs/features/multi-thread.md, docs/docs/features/prompt.md, docs/docs/features/warmup.md, docs/docs/new/about.md, docs/docs/new/architecture.md, docs/docs/new/build-source.md, docs/docs/new/faq.md, docs/docs/new/install.md, docs/docs/new/model-cycle.md, docs/docs/new/quickstart.md, docs/docusaurus.config.js, docs/static/robots.txt
PR Description: Migrate SEO improvements from Jan to Nitro
Testing:
=> feat: improve SEO for nitro

.github/runners/actions-runner-ubuntu-cuda-11-7.dockerfile, .github/runners/actions-runner-ubuntu-cuda-12-0.dockerfile, .github/runners/actions-runner-windows-cuda-11-7.dockerfile, .github/runners/actions-runner-windows-cuda-12-0.dockerfile, .github/workflows/build.yml
Fix CI run failed by upgrade cuda to 11.7
=> Fix upgrade cuda to 11.7

README.md, controllers/llamaCPP.cc, examples/grammars/json.gbnf
This PR adds support for gbnf grammars from upstream llama.cpp.
Addresses #347
=> add support for gbnf grammar

controllers/llamaCPP.cc
checking model loaded first in embedding call, otherwise nitro hang
=> add checking model loaded first in embedding call

controllers/llamaCPP.cc, controllers/llamaCPP.h
- Make use of smart pointers, avoid dereferrence in llama cpp to keep consistency
- Seperate implementation and handler logic
=> 417 feat refactor some parts of the code

controllers/llamaCPP.cc, controllers/llamaCPP.h
chunked_content_provider lambda race condition issue when: 
- T1: R1 start -> create run loop lambda and request completion. 
streaming = true | serial queue busy = true.
- T2: R1 done ->  
streaming = false | serial queue busy = false | stop = true (cancel completion request)
- T3: R1 run loop still run -> 
recreate request completion for a `completed request`? -> `zombie request` (sus memory leak?).
- T2: R1 completion request cancelled, R2 come -> llama.next_result error -> `jump in a loop`, R1 back to run loop and create new request completion -> 
- T1.5: lost connection -> R1 cancel request in progress -> R2 come & create completion -> single_queue_is_busy true, next_result error -> `jump in a loop` R3 come, stuck.
1. Its better to not create completion request within lambda, should …
=> fix: race condition issue

controllers/llamaCPP.cc, controllers/llamaCPP.h
- Deprecate shared single_queue_busy state & SerialTaskQueue since it would not work with cont_batching = true and n_parallel > 1.
- Deprecate instance's is_stopped state, better using inferenceStatus enum.
- Introduce ConcurrentTaskQueue to handle tasks with the workers number = n_parallel.
- No complicated state handling, put into the queue and it just work (inference & embedding).
Test results
- n_parallel = 1 & cont_batching = false
```
|        T1          |       T2           |       T3          |       T4          |
|--------------------|--------------------|-------------------|-------------------|
| Send chat comp.    | Send chat          | A1 completed      | A2 completed      |
| request A1         | comp. request A2   | A2 started        |                   |
| …
```
=> refactor: simplify state with queued system

controllers/llamaCPP.cc
Fixed an issue where nitro lost the [DONE] token EOS
Fixes #445
=> fix: missing [DONE] token EOS

.github/workflows/build.yml
- Address vulkan build fail issue
Vulkan SDK 1.3.275.0
=> fix: vulkan build failed

CMakeLists.txt, common/base.h, controllers/llamaCPP.cc, controllers/llamaCPP.h, models/chat_completion_request.h
Should not handle request body from controller's handler otherwise it bloats the controller implementation
```c++
#pragma once
#include <drogon/HttpController.h>
namespace inferences {
struct ChatCompletionRequest {
bool stream = false;
int max_tokens = 500;
float top_p = 0.95;
float temperature = 0.8;
float frequency_penalty = 0;
float presence_penalty = 0;
Json::Value stop = Json::Value(Json::arrayValue);
Json::Value messages = Json::Value(Json::arrayValue);
};
}  // namespace inferences
namespace drogon {
template <>
inline inferences::ChatCompletionRequest fromRequest(const HttpRequest& req) {
auto jsonBody = req.getJsonObject();
inferences::ChatCompletionRequest completion;
if (jsonBody) {
completion.stream = (*jsonBody).get("stream", false).asBool();
completion.max_tokens = …
```
=> refactor: parameter mapping - model entity

install.sh
Closes https://github.com/janhq/nitro/issues/344 Closes https://github.com/janhq/nitro/issues/420
=> Set the CUDA version in the release URL

.github/workflows/build.yml, CMakeLists.txt, audio.md, context/llama_server_context.h, controllers/llamaCPP.cc, docs/docs/new/build-source.md, examples/example-docker/cuda.Dockerfile
Issues link: https://github.com/janhq/nitro/issues/473
Relevant upstream PRs:
- [Rename `llama_kv_cache_seq_shift` => `llama_kv_cache_seq_add`.](https://github.com/ggerganov/llama.cpp/pull/5691)
- [Rename flag `LLAMA_CUBLAS` => `LLAMA_CUDA` and `GGML_USE_CUBLAS` to `GGML_USE_CUDA`.](https://github.com/ggerganov/llama.cpp/pull/6299)
- [Rename flag `WHISPER_CUBLAS` => `WHISPER_CUDA`.](https://github.com/ggerganov/whisper.cpp/pull/2001)
- [Fix embed path for macOS-silicon.](https://github.com/ggerganov/llama.cpp/pull/6015)
- [Remove unused `mul_mat_q`](https://github.com/ggerganov/llama.cpp/pull/5772)
=> chore: Pump `llama.cpp` version

context/llama_server_context.h, controllers/llamaCPP.cc, controllers/llamaCPP.h, utils/logging_utils.h, utils/nitro_utils.h
Issue link: https://github.com/janhq/nitro/issues/378
- Add more logs for the API responses.
- Remove some redundant logs.
=> feat: Add more logs for `llamaCPP` and `llama_server`

CMakeLists.txt
Issue link: https://github.com/janhq/nitro/issues/481
- Remove `LLAMA_BUILD_EXAMPLES` 
- Add `llama.cpp/examples/llava` subdirectory.
=> feat: Reduce redundant build steps

utils/nitro_utils.h
Issue link: https://github.com/janhq/nitro/issues/465
=> fix: Update content-type for responses

install.sh
This pull request addresses an issue from pull request #464, which caused Nitro software installation failures due to a missing AVX version specification.
I've updated the script to automatically detect the best AVX version using `/proc/cpuinfo` if you are on Linux. I tested this, and it is working on my Linux machine and MacBook. (I also did something similar in pull request #469, but that one was for Windows 😉)
Feel free to contact me if you have any issues! 😄
=> Add AVX support for Linux in `install.sh`

context/llama_server_context.h, controllers/llamaCPP.cc, controllers/llamaCPP.h
Changes in llama.cpp require our interface changes.
To load the embedding model, need to set embedding flag to true, for example:
```
{
"llama_model_path": "e:/workspace/model/nomic-embed-text-v1.5.f16.gguf",
"ctx_len": 5,
"ngl": 0,
"n_parallel": 1,
"embedding": true
} 
```
=> fix: make embedding work again

context/llama_server_context.h, controllers/llamaCPP.cc
blocking on multiple ends, commands R , multiple other cache bugs so we need to sacrifice cache perfomance over feature first
=> hotfix: will always be cleaning cache

controllers/llamaCPP.cc, controllers/llamaCPP.h
Issue: stream and non-stream requests are not in the same thread right now. That leads to the `Error during inference` error, only happen on some old machines when we send non-stream request and the stream response is not completed yet.
```
20240413 08:01:52.241000 UTC 1476 INFO  Request 1: Reached result stop - llamaCPP.cc:387
20240413 08:01:52.241000 UTC 1476 INFO  Request 1: End of result - llamaCPP.cc:353
20240413 08:01:52.273000 UTC 10300 INFO  Request 1: Task completed, release it - llamaCPP.cc:431
20240413 08:01:52.273000 UTC 10300 INFO  Request 1: Inference completed - llamaCPP.cc:434
20240413 08:01:53.261000 UTC 1476 DEBUG [fromRequest] Request: {"messages":[{"role":"system","content":"The conversation below is for a text summarization, user asks assistant to summarize a text and …
```
=> fix: race condition between stream and non-stream inference

README.md, context/llama_server_context.h, controllers/llamaCPP.cc, controllers/llamaCPP.h
For model like nomic-embed-text-v1.5.f16.gguf, we skip warm up.
Also change the API to send_embedding for non-logits model.
=> fix: embedding fixup for nomic-embed-text model

context/llama_server_context.h, controllers/llamaCPP.cc, controllers/llamaCPP.h
Embedding model does not support completion, so should reject completion request.
=> fix: reject completion request for embedding model

.github/scripts/e2e-test-llama-linux-and-mac.sh, controllers/llamaCPP.cc
Currently e2e scripts can be hang because we unload model when still receiving the stream. Change to non-stream to temporary fix issue.
=> fix: app hangs if we unload model during stream completion 

.github/scripts/e2e-test-llama-linux-and-mac.sh, .github/scripts/e2e-test-llama-windows.bat, cortex-cpp/controllers/server.h, cortex-cpp/engines/cortex.llamacpp/engine.cmake
cortex.llamacpp is now supporting multiple models, we need to change method of `unloadmodel` and `modelstatus` to POST.
Sample requests for multiple models feature:
load model:
```
curl http://localhost:3928/inferences/server/loadmodel \
-H 'Content-Type: application/json' \
-d '{
"llama_model_path": "/model/llama-2-7b-model.gguf",
"model_alias": "llama-2-7b-model",
"model_type": "llm" // use 'embedding` for embedding model
}'
``` 
unload model
```
curl http://localhost:3928/inferences/server/unloadmodel \
-H 'Content-Type: application/json' \
-d '{
"model": "llama-2-7b-model"
}'
```
=> feat: change unload model and model status to POST

cortex-js/src/command.module.ts, cortex-js/src/domain/abstracts/engine.abstract.ts, cortex-js/src/domain/abstracts/oai.abstract.ts, cortex-js/src/infrastructure/commanders/inference.command.ts, cortex-js/src/infrastructure/controllers/chat.controller.ts, cortex-js/src/usecases/chat/chat.module.ts, cortex-js/src/usecases/chat/chat.usecases.ts
https://github.com/janhq/cortex/assets/10397206/68fe724f-41ca-4237-b208-778d45218462
=> feat: add CLI for chat

cortex-js/src/infrastructure/commanders/basic-command.commander.ts, cortex-js/src/infrastructure/commanders/init.command.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts
It's to fix an issue where program looks for an incorrect engine url
=> fix: correct cuda version lookup

README.md, cortex-js/README.md
Before installation, ensure that you have installed the following:
- **Node.js**: Required for running the installation.
- **NPM**: Needed to manage packages.
- **CPU Instruction Sets**: Available for download from the [Cortex GitHub Releases](https://github.com/janhq/cortex/releases) page.
<aside>
💡 The **CPU instruction sets** are not required for the initial installation of Cortex. This dependency will be automatically installed during the Cortex initialization if they are not already on your system.
</aside>
Ensure that your system meets the following requirements to run Cortex:
- **OS**:
- MacOSX 13.6 or higher.
- Windows 10 or higher.
- Ubuntu 12.04 and later.
- **RAM (CPU Mode):**
- 8GB for running up to 3B models.
- 16GB for running up to 7B models.
- 32GB for running up to 13B …
=> chore: update README

README.md, cortex-js/README.md
- Update README.md
- Closes #
- Closes #
=> chore: update README.md

cortex-js/package.json, cortex-js/src/domain/abstracts/oai.abstract.ts, cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/types/model-tokenizer.interface.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/models/models.usecases.ts
- allow user to pull model from janhq from HuggingFace
https://github.com/janhq/cortex/assets/10397206/70f7af9e-3c86-4dbd-8322-91cf43a44987
=> feat: pull model yaml from hf

cortex-js/package.json
build extension able to run on windows
- Closes #
- Closes #
=> build extension able to run on windows

cortex-js/package.json, cortex-js/src/app.module.ts, cortex-js/src/command.module.ts, cortex-js/src/domain/config/config.interface.ts, cortex-js/src/file-manager/file-manager.module.ts, cortex-js/src/file-manager/file-manager.service.spec.ts, cortex-js/src/file-manager/file-manager.service.ts, cortex-js/src/infrastructure/commanders/usecases/cli.usecases.module.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/database/database.module.ts, cortex-js/src/infrastructure/database/sqlite-database.providers.ts, cortex-js/src/infrastructure/providers/cortex/cortex.module.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/main.ts, cortex-js/src/usecases/cortex/cortex.module.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/models/models.module.ts, cortex-js/src/usecases/models/models.usecases.ts
- Store cortex data in a separate directory so user can freely upgrade their cortex without worry losing their data.
- Store cortex setting under `~/.cortexrc`. Consider removing suffix `rc` because it seems abit weird.
=> feat: add cortex data folder

cortex-js/src/infrastructure/commanders/chat.command.ts, cortex-js/src/infrastructure/commanders/usecases/chat.cli.usecases.ts, cortex-js/src/infrastructure/controllers/models.controller.ts, cortex-js/src/infrastructure/controllers/threads.controller.ts
```shell
cortex chat -m hello there
cortex chat -a -m hello there
```
- Closes #
- Closes #
=> chore: cortex chat revamp with options

cortex-js/src/command.module.ts, cortex-js/src/infrastructure/commanders/cortex-command.commander.ts, cortex-js/src/infrastructure/commanders/kill.command.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/models/model-stop.command.ts, cortex-js/src/infrastructure/commanders/ps.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/infrastructure/commanders/usecases/cli.usecases.module.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/ps.cli.usecases.ts, cortex-js/src/infrastructure/controllers/cortex.controller.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/models/models.usecases.ts
- Add `cortex ps` command support that fetches all models loaded from the Cortex-CPP process.
- Added `cortex models start` `-a` argument to support attach / detach option (detach by default)
- Fixed `cortex models start | stop` error outputs
- Added `cortex kill` - it's to kill any running cortex processes
=> feat: ps command support

cortex-js/src/infrastructure/commanders/chat.command.ts, cortex-js/src/infrastructure/commanders/models/model-list.command.ts, cortex-js/src/infrastructure/commanders/models/model-stop.command.ts, cortex-js/src/infrastructure/commanders/usecases/chat.cli.usecases.ts
* Improved the `cortex chat` command to be smarter:
+ `cortex chat` without model_id: looks for an active running model or selects a running model from the list.
+ `cortex chat message` and `cortex chat -m message` work the same (and do not look for a non-existent model with that input).
* Fixed an issue where Cortex is killed after a chat session ends.
* Fixed an issue where stopping a model also kills Cortex.
- Closes #
- Closes #
=> chore: cortex chat enhancement

cortex-js/src/infrastructure/commanders/chat.command.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/usecases/ps.cli.usecases.ts
- This PR is to support selecting a model prompt when running `cortex models start`
- 
- Closes #
- Closes #
=> fix: allow users to select a model to start

cortex-js/src/infrastructure/controllers/chat.controller.ts, cortex-js/src/main.ts
- Remove the Cortex tag description because the Cortex endpoints are deprecated
- Add desc for chat completions endpoint
- Closes #
- Closes #
=> api: Update the API decorator

cortex-js/src/infrastructure/commanders/cortex-command.commander.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/usecases/models/models.usecases.ts
- Add model selection into `cortex run`
- Add `cortex version`
- Closes #
- Closes #
=> chore: Update the run command to allow model selection and add the Cortex version.

README.md, cortex-js/README.md, cortex-js/package.json, cortex-js/src/infrastructure/commanders/init.command.ts, cortex-js/src/infrastructure/commanders/types/init-options.interface.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts
- This PR adds a post-install script that downloads the corresponding Cortex dependencies based on the user's hardware specs during installation. So, after installing Cortex from the npm repo, there is no need to run `cortex init` to get started.
- Removed cortex init step from README
Support: 
- Nvidia GPUs (ROCm is in progress)
- CPU with AVX-512, AVX2, AVX
- Apple Silicon
=> feat: cortex post-install script - init silently on install

cortex-js/src/extensions/groq/package.json, cortex-js/src/extensions/mistral/package.json, cortex-js/src/extensions/openai/package.json, cortex-js/src/infrastructure/commanders/chat.command.ts, cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/models/model-stop.command.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/commanders/utils/app-path.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/infrastructure/repositories/extensions/extension.repository.ts
- Fixed #650 - If no message is input, it should enter interactive shell mode (as shown).
- Fixed #649 - Due to bad model input extraction (#605), it slows down the model pull request and adds an extra branch to normal HF repositories.
- Fixed #643 - Due to duplicate code, resolving PR conflict.
- Closes #
- Closes #
=> fix: cortex chat without arguments should work

cortex-js/package.json, cortex-js/src/infrastructure/controllers/assistants.controller.spec.ts, cortex-js/src/infrastructure/controllers/assistants.controller.ts, cortex-js/src/infrastructure/controllers/chat.controller.spec.ts, cortex-js/src/infrastructure/controllers/messages.controller.spec.ts, cortex-js/src/infrastructure/controllers/messages.controller.ts, cortex-js/src/infrastructure/controllers/models.controller.spec.ts, cortex-js/src/infrastructure/controllers/threads.controller.spec.ts, cortex-js/src/infrastructure/database/sqlite-database.providers.ts, cortex-js/src/infrastructure/dtos/chat/create-chat-completion.dto.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/main.ts, cortex-js/src/usecases/assistants/assistants.usecases.spec.ts, cortex-js/src/usecases/chat/chat.usecases.spec.ts, cortex-js/src/usecases/cortex/cortex.usecases.spec.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/messages/messages.usecases.spec.ts, cortex-js/src/usecases/models/models.usecases.spec.ts, cortex-js/src/usecases/threads/threads.usecases.spec.ts, cortex-js/test/jest-e2e.json, cortex-js/test/models.e2e-spec.ts
=> fix: correct tests setup

README.md, cortex-js/README.md
-add a note for more details
- Closes #
- Closes #
=> readme: add a note for more details

cortex-js/src/infrastructure/controllers/threads.controller.ts, cortex-js/src/infrastructure/dtos/page.dto.ts, cortex-js/src/main.ts, cortex-js/src/usecases/threads/threads.usecases.ts
- Add query messages of thread.
=> feat: add query messages of thread api

cortex-js/src/file-manager/file-manager.service.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/infrastructure/commanders/utils/model-parameter.parser.ts
- Fixed an issue where pre_prompt does not work with model start
- Closes #
- Closes #
=> fix: add pre_prompt to engine settings

.github/workflows/cortex-cpp-build.yml, .github/workflows/cortex-cpp-quality-gate.yml, cortex-cpp/engines/cortex.llamacpp/engine.cmake
- Change Windows CI runner to `windows-cuda-12-0` because `windows-latest` makes our server crashes after some `poll` and `select` calls.
- https://github.com/janhq/cortex.llamacpp/releases/tag/v0.1.17
- Closes #
- Closes #
=> chore: cortex.llamacpp to version 0.1.17

cortex-js/src/domain/models/model.interface.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/ps.cli.usecases.ts, cortex-js/src/infrastructure/constants/cortex.ts, cortex-js/src/infrastructure/dtos/chat/create-chat-completion.dto.ts, cortex-js/src/infrastructure/dtos/cortex/start-cortex.dto.ts, cortex-js/src/infrastructure/dtos/models/model-settings.dto.ts, cortex-js/src/infrastructure/dtos/models/model.dto.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/usecases/threads/threads.usecases.ts
- Update the model settings and API description for advanced model load parameters.
- Closes #
- Closes #
=> chore: update models settings

README.md, cortex-js/README.md, cortex-js/src/infrastructure/controllers/embeddings.controller.ts, cortex-js/src/infrastructure/dtos/chat/embeddings-response.dto.ts, cortex-js/src/infrastructure/dtos/embeddings/embeddings-request.dto.ts, cortex-js/src/main.ts
- Update the API description for the Embeddings
- Update the dependencies
- Closes #
- Closes #
=> api: Update the API description

cortex-js/src/infrastructure/commanders/benchmark.command.ts, cortex-js/src/infrastructure/commanders/usecases/benchmark.cli.usecases.ts, cortex-js/src/infrastructure/constants/benchmark.ts
- The changes aim to improve the benchmarking functionality by adding new options, refining the command structure, and enhancing the output format.
- Closes #
- Closes #
=> chore: add benchmark options

cortex-js/src/download-manager/download-manager.service.ts
Since #686, all of the cli download operations stopped working. This is to temporary comment out the broken code block til it's fixed.
- Closes #
- Closes #
=> chore: comment out hacky latest download state update that break the downloading flow

cortex-js/src/app.module.ts, cortex-js/src/infrastructure/commanders/ps.command.ts, cortex-js/src/infrastructure/commanders/serve.command.ts, cortex-js/src/infrastructure/commanders/usecases/ps.cli.usecases.ts, cortex-js/src/infrastructure/constants/cortex.ts, cortex-js/src/infrastructure/controllers/process.controller.ts, cortex-js/src/infrastructure/controllers/status.controller.ts, cortex-js/src/main.ts, cortex-js/src/usecases/assistants/assistants.module.ts, cortex-js/src/usecases/chat/chat.module.ts, cortex-js/src/usecases/models/models.module.ts, cortex-js/src/usecases/threads/threads.module.ts
This PR is intended to refactor the use cases to eliminate their dependency on controllers. According to the principles of the Clean Architecture, controllers should be defined at the app/framework level and not in the use cases.
This PR also added support for Cortex Serve with detach mode and additional status indicators in Cortex PS to display the API server's online status. Also added stop api server option `cortex serve stop`.
- Closes #
- Closes #
=> feat: add cortex serve detach option - add health check and stop api endpoints

.github/workflows/nightly-build.yml, .github/workflows/nightly.yml
Add nightly build for cortex to pull latest nightly of cortex.llamacpp
- Closes #
- Closes #
=> Add nightly build for cortex to pull latest nightly of cortex.llamacpp

.github/workflows/cortex-cpp-build.yml, .github/workflows/nightly-build.yml, .github/workflows/nightly.yml
Fix nightly
- Closes #
- Closes #
=> Fix nightly

cortex-js/src/app.module.ts, cortex-js/src/infrastructure/commanders/serve.command.ts
- As a user, when I run cortex serve, I would like to see it run in attached mode, allowing me to observe the incoming requests
- Closes #
- Closes #
=> fix: cortex serve should run in attached mode by default

.github/workflows/cortex-cpp-build.yml, .github/workflows/nightly-build.yml
- Fix windows codesign must run on cmd
- Closes #
- Closes #
=> Fix windows codesign must run on cmd

cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/infrastructure/constants/cortex.ts, cortex-js/src/infrastructure/constants/huggingface.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/infrastructure/repositories/extensions/extension.repository.ts, cortex-js/src/usecases/chat/chat.usecases.ts, cortex-js/src/usecases/models/models.usecases.ts, cortex-js/src/utils/huggingface.ts
- This PR ships the ONNX runtime on Windows:
- The ONNX engine is quite lightweight (14mb), so we've opted to bundle it alongside the llama.cpp engine.
- Post-install step would download both engines to cortex directory.
- During installation, a few files that do not belong to the engine will be moved accordingly by cortex-cpp.
NOTES: Since this PR, we have switched to using `cortexhub` as our default hub instead of the janhq HF repo
- Closes #
- Closes #
=> feat: ship ONNX runtime on Windows

cortex-js/src/usecases/cortex/cortex.usecases.ts
- This is to address the issue where Cuda toolkit dependencies do not work on Linux
- Closes #
- Closes #
=> chore: update env for cuda toolkit dependencies and tensorrt-llm

cortex-js/installer.iss, cortex-js/package.json
- Enable Cortex distribution on Windows using an MSI installer
Notes: 
- The installation step adds the Cortex location to the PATH environment variable and installs required dependencies (via "cortex init").
- Closes #
- Closes #
=> feat: add inno installer script

.github/workflows/cortex-js-openai-coverage.yml
=> chore: change --host to -- address

.github/workflows/cortex-build.yml
- Fixed an issue where package.json's version does not update on Windows build
- Closes #
- Closes #
=> fix: cortex version on windows

cortex-js/package.json, cortex-js/src/command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts
- Suppress warnings on Cortex installed via NPM.
- Fix broken npm postinstall script
- Fix tensorrt-llm LD_LIBRARY_PATH
- Closes #
- Closes #
=> fix: cortex node suppress warning

README.md, cortex-js/src/main.ts
- Add log message to inform about Swagger UI on `cortex-js/src/main.ts`
- Update information to access Cortex API Server & Swagger UI on `README.md`
- Closes #746
=> chore: Add Swagger UI Log Message and Update `README.md` with API Access Information

cortex-js/src/infrastructure/commanders/benchmark.command.ts, cortex-js/src/infrastructure/commanders/types/benchmark-config.interface.ts, cortex-js/src/infrastructure/commanders/usecases/benchmark.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts
Also fixed `cortex benchmark model` issue
- Closes #
- Closes #
=> chore: add dependency instructions

.github/workflows/cortex-build.yml, cortex-js/Makefile
- This is to add a MacOS PKG installer to the Cortex release
- Closes #
- Closes #
=> chore: add MacOS pkg installer

.github/workflows/cortex-build.yml, cortex-js/control.template
- Add Installer for linux
- Closes #
- Closes #
=> Add Installer for linux

cortex-js/src/domain/abstracts/oai.abstract.ts, cortex-js/src/extensions/groq.engine.ts, cortex-js/src/extensions/mistral.engine.ts, cortex-js/src/extensions/openai.engine.ts, cortex-js/src/infrastructure/commanders/usecases/chat.cli.usecases.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts
- This is the follow-up PR to #782, which ensures remote engines can work with corresponding configurations.
- Closes #
- Closes #
=> feat: cortex supports remote engines

cortex-js/src/infrastructure/commanders/embeddings.command.ts, cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/serve.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/infrastructure/commanders/usecases/chat.cli.usecases.ts, cortex-js/src/main.ts, cortex-js/src/usecases/models/models.usecases.ts
- Gate ONNX models pull on MacOS and Linux
- Gate Tensorrt-LLM models pull on MacOS
- Clearer error message
- Closes #
- Closes #
=> chore: error handling

cortex-js/src/infrastructure/constants/cortex.ts
=> fix: api path - add v1 component

cortex-js/src/extensions/extensions.module.ts, cortex-js/src/extensions/groq.engine.ts, cortex-js/src/extensions/mistral.engine.ts, cortex-js/src/extensions/openai.engine.ts, cortex-js/src/usecases/configs/configs.module.ts, cortex-js/src/usecases/configs/configs.usecase.ts
=> chore: correct engine reload on config save

cortex-js/src/domain/models/model.event.ts, cortex-js/src/infrastructure/controllers/models.controller.ts, cortex-js/src/infrastructure/services/download-manager/download-manager.service.ts, cortex-js/src/usecases/models/models.usecases.ts
=> fix: return immediately when invoke download model api

cortex-js/src/domain/models/huggingface.interface.ts, cortex-js/src/domain/models/model.event.ts, cortex-js/src/domain/models/model.interface.ts, cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/serve.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/infrastructure/constants/benchmark.ts, cortex-js/src/infrastructure/constants/huggingface.ts, cortex-js/src/infrastructure/controllers/models.controller.ts, cortex-js/src/infrastructure/dtos/models/model-artifact.dto.ts, cortex-js/src/infrastructure/services/download-manager/download-manager.service.ts, cortex-js/src/main.ts, cortex-js/src/usecases/models/models.usecases.ts, cortex-js/src/utils/app-path.ts, cortex-js/src/utils/huggingface.ts, cortex-js/src/utils/model-check.ts
- Allow clients to pull a model via a REST API
- Closes #
- Closes #
=> refactor: model pull api and post processing

cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/infrastructure/commanders/usecases/benchmark.cli.usecases.ts, cortex-js/src/infrastructure/constants/huggingface.ts, cortex-js/src/utils/huggingface.ts
- Updated model repo to cortexso
- Closes #
- Closes #
=> chore: quick update model repo to cortexso

cortex-js/src/command.module.ts, cortex-js/src/infrastructure/commanders/engines.command.ts, cortex-js/src/infrastructure/commanders/engines/engines-init.command.ts, cortex-js/src/infrastructure/commanders/kill.command.ts, cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/infrastructure/commanders/test/helpers.command.spec.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/ps.cli.usecases.ts, cortex-js/src/infrastructure/repositories/extensions/extension.repository.ts, cortex-js/src/usecases/chat/chat.usecases.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/models/models.usecases.ts
- This is to support `cortex engines init` command, for the case that support engines ahead of time, eg docker build.
```
// Llama.cpp engine
cortex engines init cortex.llamacpp
// ONNX engine
cortex engines init cortex.onnx
// Tensorrt-LLM engine
cortex engines init cortex.tensorrt-llm
```
// DO NOT INIT REMOTE ENGINES
- Closes #809
=> feat: support cortex engines init command

cortex-js/src/usecases/models/models.usecases.ts, cortex-js/src/utils/huggingface.ts
- Fixed an issue where model id parsing parses a wrong model id
- Closes #
- Closes #
=> fix: model id parsing breaks model pull

cortex-js/src/infrastructure/commanders/engines/engines-init.command.ts, cortex-js/src/infrastructure/commanders/models.command.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/infrastructure/commanders/usecases/chat.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/models/models.usecases.ts, cortex-js/src/utils/logs.ts
chore: error handling - cortex run error outputs and logs file
Added error outputs and log file
NOTES: Removed `Checking model files for existing...`
`cortex run`: Loading status
`cortex run`: Error outputs from cortex-js
`cortex run`: Error outputs from cortex-cpp
`cortex pull`: with remote URL 
- Closes #801
- Closes #776
=> chore: error output logs for cortex run

cortex-js/package.json
(node:66516) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
- Closes #
- Closes #
=> fix: resolve deprecated module npm

cortex-js/src/command.ts
=> fix: another attempt to suppress warning

cortex-js/src/command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/utils/model-check.ts
- It's to raise error even before pulling
- Closes #
- Closes #
=> fix: gate onnx and tensorrt-llm run on darwin

cortex-cpp/README.md, cortex-js/src/infrastructure/commanders/configs.command.ts, cortex-js/src/infrastructure/commanders/engines.command.ts, cortex-js/src/infrastructure/commanders/models.command.ts, cortex-js/src/infrastructure/commanders/models/model-list.command.ts
This is to add help information when users access root commands (models, engines, configs)
`cortex models list` should show model name
- Closes #754
- Closes #836
=> chore: #754 - add help information into root commands

cortex-js/package.json
- Playground is broken on prebuilt binaries & installers
- Closes #
- Closes #
=> fix: missing swagger UI assets on prebuilt binaries

cortex-js/src/infrastructure/commanders/init.command.ts, cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts, cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts, cortex-js/src/infrastructure/services/file-manager/file-manager.service.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/models/models.usecases.ts, cortex-js/src/utils/logs.ts
- Fixed an issue where cortex models start can just attach once. Where cortex-cpp server shell injection can just done once. Now it observes log file instead. So can attach from any processes.
- Fixed an issue where the model loading indicator keeps showing when the model is already loaded before.
- Added `Model is running` indicator in attached mode
- Closes #644
=> fix: #644 - model start attach mode can just work once

cortex-js/src/domain/abstracts/oai.abstract.ts, cortex-js/src/extensions/anthropic.engine.ts, cortex-js/src/extensions/groq.engine.ts, cortex-js/src/extensions/mistral.engine.ts, cortex-js/src/extensions/openai.engine.ts
Fixed an issue where all requests route to /v1/chat/completions are not processed. They all hang due to the hard-coded content-size of the request header modification.
- Broken PR: #864
- Closes #876
=> fix: chat completion endpoint is hang

README.md, cortex-js/README.md
- Add the engine section
- Simplify the Readme
- Closes #
- Closes #
=> Update the README

.github/workflows/cortex-build.yml, cortex-cpp/package.json, cortex-js/package.json, cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts
- Fixed an issue where the cortex-cpp prebuild was installed without dependencies.
- Fixed an issue where cortex pulls the incorrect cortex.llamacpp engine file on devices that do not support CUDA.
- Fixed an issue where the CI fails if the npm module has not been published yet.
- Closes #870
=> fix: cortex-cpp node prebuild dependencies

cortex-js/src/infrastructure/dtos/chat/chat-completion-message.dto.ts, cortex-js/src/infrastructure/dtos/chat/create-chat-completion.dto.ts, cortex-js/src/infrastructure/dtos/embeddings/embeddings-request.dto.ts, cortex-js/src/infrastructure/dtos/models/create-model.dto.ts, cortex-js/src/infrastructure/dtos/models/model.dto.ts, cortex-js/src/infrastructure/dtos/threads/create-thread-assistant.dto.ts
- add better example for the request body
- Closes #
- Closes #
=> add better example for the request body

cortex-js/src/domain/abstracts/oai.abstract.ts, cortex-js/src/infrastructure/controllers/chat.controller.ts, cortex-js/src/utils/request.ts
- Gated weird headers from client
- Closes #
- Closes #
=> fix: remote engines should accept normalized headers only

cortex-cpp/controllers/health.cc, cortex-cpp/controllers/server.cc, cortex-cpp/controllers/server.h, cortex-cpp/utils/cortex_utils.h
- Currently we only allow to run one engine at a time. Because cortex.trt-llm and cortex.onnx don't support embeddings yet, therefore we need to run cortex.llamacpp for embeddings along side with cortex.trt-llm/cortex.onnx for chat completions.
- This PR also includes a commit to refactor the codebase.
=> feat: support running multiple engines at the same time

cortex-js/src/infrastructure/controllers/events.controller.ts, cortex-js/src/infrastructure/services/download-manager/download-manager.service.ts
There was a legacy issue where we combined abort download event and progress event into 1 pipeline.
Download: +------A1-------A2--------A3---X
Cancel     : +---B1-----B2-------B3---------X
Problems: 
1. We use a throttle without trailing event emission.
- At X, there is no A3 event emitted (e.g., 100% or success event).
2. We add a trailing event emission.
- At A2, we abort the download process -> a B1 event is emitted, then A2 once (aborted -> downloading).
- Closes #
=> fix: download model wrong event mits

cortex-js/src/domain/abstracts/engine.abstract.ts, cortex-js/src/domain/models/model.interface.ts, cortex-js/src/infrastructure/constants/cortex.ts, cortex-js/src/infrastructure/controllers/chat.controller.spec.ts, cortex-js/src/infrastructure/controllers/chat.controller.ts, cortex-js/src/infrastructure/controllers/embeddings.controller.spec.ts, cortex-js/src/infrastructure/controllers/embeddings.controller.ts, cortex-js/src/infrastructure/dtos/messages/create-message.dto.ts, cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/usecases/chat/chat.module.ts, cortex-js/src/usecases/chat/chat.usecases.spec.ts, cortex-js/src/usecases/chat/chat.usecases.ts, cortex-js/src/usecases/models/models.usecases.ts, cortex-js/src/utils/model-parameter.parser.ts
This PR is to add model loading on the /chat/completions & /embeddings request from the JS layer.
Note: We use `cortexso/nomic-embed-text-v1` as the default embedding model, in case the model is not defined. It will automatically pull embedding model if it does not exit.
CLI update should be covered by refactoring to send REST requests.
```mermaid
sequenceDiagram
participant User
participant API_Controller
participant Engine_Server
participant Model
User->>API_Controller: Chat request
API_Controller->>Engine_Server: Check Model Running
Engine_Server-->>API_Controller: Model status
alt Model is not running
API_Controller->>Engine_Server: Start Model command
Engine_Server->>Model: Start Model
Model-->>Engine_Server: Model started
Engine_Server-->>API_Controller: Model ready
end …
```
=> chore: auto load model on /chat/completions request

cortex-js/presets/alpaca.yml, cortex-js/presets/chatml.yml, cortex-js/presets/llama3.yml, cortex-js/presets/vicuna.yml
- Tested for llama3 GGUF
- l3utterfly/phi-2-layla-v1-chatml-gguf
- Alpaca GGUF:
- Vicuna GGUF:
- Closes #
- Closes #
=> feat: Create llama3.yml presets for llama3 family

cortex-js/package.json, cortex-js/src/infrastructure/commanders/base.command.ts, cortex-js/src/infrastructure/commanders/base.subcommand.ts, cortex-js/src/infrastructure/commanders/benchmark.command.ts, cortex-js/src/infrastructure/commanders/chat.command.ts, cortex-js/src/infrastructure/commanders/cortex-command.commander.ts, cortex-js/src/infrastructure/commanders/embeddings.command.ts, cortex-js/src/infrastructure/commanders/engines/engines-get.command.ts, cortex-js/src/infrastructure/commanders/engines/engines-init.command.ts, cortex-js/src/infrastructure/commanders/engines/engines-list.command.ts, cortex-js/src/infrastructure/commanders/engines/engines-set.command.ts, cortex-js/src/infrastructure/commanders/models/model-get.command.ts, cortex-js/src/infrastructure/commanders/models/model-list.command.ts, cortex-js/src/infrastructure/commanders/models/model-pull.command.ts, cortex-js/src/infrastructure/commanders/models/model-remove.command.ts, cortex-js/src/infrastructure/commanders/models/model-start.command.ts, cortex-js/src/infrastructure/commanders/models/model-stop.command.ts, cortex-js/src/infrastructure/commanders/models/model-update.command.ts, cortex-js/src/infrastructure/commanders/run.command.ts, cortex-js/src/infrastructure/constants/cortex.ts, cortex-js/src/infrastructure/controllers/models.controller.ts, cortex-js/src/infrastructure/services/file-manager/file-manager.service.ts, cortex-js/src/usecases/engines/engines.usecase.ts
- There is no default API server configs provided 
- Should not initialize cortexjs instance root command
- Closes #
- Closes #
=> chore: update default api server config

.github/workflows/cortex-build.yml, package-managers-template/launchpad/cortexso/debian/changelog
- Change from github hotsted to macos selfhosted
- Closes #
- Closes #
=> Change from github hotsted to macos selfhosted

cortex-js/src/index.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/usecases/engines/engines.usecase.ts
- Cortex CPP service still running even when application exit
- Install cuda toolkit dependencies on tensorrt-llm engine init
- Closes #
- Closes #
=> chore: attempt to release running services on exit

cortex-js/package.json, cortex-js/src/app.ts, cortex-js/src/infrastructure/controllers/engines.controller.ts, cortex-js/src/infrastructure/controllers/models.controller.ts, cortex-js/src/infrastructure/controllers/system.controller.ts
- Update the API desc
- Remove the unused API tags
- Closes #
- Closes #
=> Update the api desc

.github/workflows/cortex-build.yml, cortex-js/installer.iss
- Fix winget PR issue
- Closes #
- Closes #
=> Fix winget PR issue

cortex-js/src/infrastructure/commanders/chat.command.ts, cortex-js/src/infrastructure/commanders/embeddings.command.ts
- Cortex chat should attach session into running models only. Or chat completion endpoint start model automatically (it's backend stuff not frontend)
- Closes #
- Closes #
=> chore: fixed an issue where cortex chat reload the running models

cortex-js/src/infrastructure/commanders/engines.command.ts, cortex-js/src/infrastructure/commanders/engines/engines-init.command.ts, cortex-js/src/infrastructure/commanders/types/init-options.interface.ts, cortex-js/src/infrastructure/controllers/engines.controller.ts, cortex-js/src/infrastructure/dtos/engines/engines.dto.ts, cortex-js/src/usecases/engines/engines.usecase.ts
- Able to specify an engine version to pull
- Closes #
- Closes #
=> chore: specify engine version to pull

cortex-js/uninstall.js
- Attempt Destroy cpp and js processes on uninstall
- #917
=> chore: destroy dangling processes on uninstall

cortex-js/src/domain/abstracts/oai.abstract.ts, cortex-js/src/extensions/anthropic.engine.ts, cortex-js/src/extensions/cohere.engine.ts, cortex-js/src/extensions/extensions.module.ts, cortex-js/src/extensions/martian.engine.ts, cortex-js/src/extensions/nvidia.engine.ts, cortex-js/src/extensions/openrouter.engine.ts, cortex-js/src/infrastructure/commanders/types/engine.interface.ts, cortex-js/src/infrastructure/controllers/chat.controller.ts, cortex-js/src/infrastructure/services/resources-manager/resources-manager.service.ts
- support martian, nvidia engine
- fix chat with anthropic, cohere engine
- Closes #
- Closes #
=> feat: support martian nvidia engine

cortex-js/src/usecases/engines/engines.usecase.ts
- Fixed an issue where client sends empty body should also provide best default engine init options
- Closes #
- Closes #
=> fix: cortex engines init api with empty body should init default options

cortex-js/src/infrastructure/commanders/services/chat-client.ts
- This is to normalize message content request, since jan is not handled message content array type yet. 
- Closes #
- Closes #
=> fix: create message request with string content instead of array

cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts, cortex-js/src/infrastructure/repositories/extensions/extension.repository.ts, cortex-js/src/usecases/engines/engines.usecase.ts
- This PR is to persist the engine version and display it accordingly, instead of just returning a hardcoded version.
- Closes #
- Closes #
=> fix: persists engine version on init

cortex-js/src/app.ts, cortex-js/src/index.ts, cortex-js/src/main.ts
- correct swagger port
- Closes #
- Closes #
=> fix: correct swagger port

cortex-js/src/command.ts, cortex-js/src/index.ts, cortex-js/src/infrastructure/commanders/cortex-command.commander.ts, cortex-js/src/infrastructure/commanders/serve-stop.command.ts, cortex-js/src/main.ts, cortex-js/src/usecases/cortex/cortex.usecases.ts, cortex-js/src/utils/cortex-cpp.ts
- It's hard to distinguish what processes are running which service. Let's put a title on each service.
- Closes #
=> chore: name cortex processes

.github/workflows/cortex-build.yml, .github/workflows/cortex-js.yml
- cortex js allow tag x.y.z-t
- Closes #
- Closes #
=> cortex js allow tag x.y.z-t

cortex-js/src/usecases/models/models.usecases.ts, cortex-js/src/utils/cuda.ts, cortex-js/src/utils/huggingface.ts
- It flashes for hundred milliseconds
- Closes #
- Closes #
=> fix: hide gpu check windows

cortex-js/src/index.ts, cortex-js/src/utils/logs.ts
- This will update supported JS import configurations.
- Closes #
- Closes #
=> chore: support more configurations via direct js import

.github/workflows/cortex-build.yml, cortex-js/Makefile
- After reduced build targets, need to fix the file lookup
- Closes #
- Closes #
=> fix: binary file lookup

cortex-cpp/addon.cc, cortex-cpp/main.cc
Upload folder is redundant because we don't upload any files
=> fix: remove uploads_folder_path

cortex-js/src/domain/models/resource.interface.ts, cortex-js/src/infrastructure/services/resources-manager/resources-manager.service.ts, cortex-js/src/usecases/models/models.usecases.ts
- /system/events/resources should return GPUs information
- Closes #
- Closes #
=> chore: system resource events should include gpu system information

cortex-js/package.json, cortex-js/src/usecases/engines/engines.usecase.ts, cortex-js/src/utils/init.ts
- Follow up PR of [#avx](https://github.com/janhq/cortex.llamacpp/pull/172)
As agreed, there is little difference between CPU instructions when running the Cortex CPP benchmark. We revert to the no-AVX binary and rely on GPU performance.
 
- Closes #899
=> chore: fallback noavx binary

cortex-cpp/package.json, cortex-js/package.json
- Resolve comment in brew PR
- Closes #
- Closes #
=> Resolve comment in brew PR

cortex-js/package.json, cortex-js/src/domain/models/model.interface.ts, cortex-js/src/domain/repositories/model.interface.ts, cortex-js/src/infrastructure/commanders/run.command.ts, cortex-js/src/infrastructure/controllers/models.controller.ts, cortex-js/src/infrastructure/repositories/models/model.repository.ts, cortex-js/src/usecases/models/models.usecases.ts
- support to start model by file path
- Closes #
- Closes #
=> feat: support to start model by file path
