- config.json
To fix this issue
https://github.com/janhq/jan/issues/279
> feat: avoid pointing to computer host, avoid showing warning network message

- .github/release-drafter.yml
- .github/workflows/build.yml
This PR does:
- Refactor CICD by trigger by tag and versioning with segmantic
- Add Release note template
> Refactor CICD: change trigger by tag and add release note template

- .github/release-drafter.yml
- .github/workflows/build.yml
Fix error release name in release drafter template
> Fix error release name in release drafter template

- CMakeLists.txt
- controllers/health.cc
- controllers/llamaCPP.cc
- utils/nitro_utils.h
this will support allow all cors
> feat: nitro add debug build

- .github/workflows/build.yml
> feat: CI/CD and windows with/ without GPU

- controllers/llamaCPP.cc
- controllers/llamaCPP.h
> pump llama cpp latest version

- controllers/llamaCPP.cc
will add logit bias if there is need arise + meaningful usage (too few people use this feature)
> add extra params

- .github/workflows/build.yml
Nitron linux allow all cors for cloud-native
> Nitron linux allow all cors for cloud-native

- .github/workflows/build.yml
Add c/c++ file extension trigger for nitro CI:
- `.cc`
- `.cxx`
> Add c/c++ file extension trigger for nitro CI

- controllers/llamaCPP.h
100% compatible with openai down to the path
> feat: add openai compatible path

- .github/workflows/build.yml
Correct condition for nighty build to trigger noti-discord
> Correct condition for nighty build to trigger noti-discord

- controllers/llamaCPP.cc
- This issue also seemed not addressed on the upstream repo, so i need to fix it on nitro level
> bug: Fix caching compatibility issues regarding system prompt

- .github/workflows/build.yml
Fix error nitro GPU run failed on linux
> Fix error nitro GPU run failed on linux

- controllers/llamaCPP.h
-Also update the version of llama cpp to support phi-2
> 284 bug inferencing not stopping background task

- controllers/llamaCPP.cc
- main.cc
- Use number of logical cores to be a threadpool of drogon (to handle things outside of inference)
- n_parallel dependency on drogon thread_num has been removed, manually set from now on
@hahuyhoang411 please check and update the docs
> 290 feat proper threadpool allocations

- controllers/llamaCPP.cc
- controllers/llamaCPP.h
Implement a temporary solution to enable queue of chat completion request to avoid empty message when single threaded usage
> 215 epic queue system

- README.md
- docs/docs/examples/chatboxgpt.md
- docs/docs/features/grammar.md
- docs/docs/features/load-unload.md
- docs/docs/features/multi-thread.md
- docs/docs/features/self-extend.md
- docs/sidebars.js
PR documentation for this issue: https://github.com/janhq/nitro/issues/352
> Documentation 0.2.10

- controllers/llamaCPP.cc
- `request_cancel` should be called on done.
- error does not goes through callback
> chore: release request upon completion

- .github/workflows/build.yml
- CMakeLists.txt
issue link: https://github.com/janhq/nitro/issues/482
> chore: Refactor `workflows/build.yml` and remove manual build flags

- context/llama_server_context.h
- controllers/llamaCPP.cc
- controllers/llamaCPP.h
This reverts commit 09d7a093526c21cc7cb06822480e689287dff72b.
> Revert "fix: make embedding work again"

- .github/workflows/build.yml
Has some errors when we move the windows cuda build to new machine.
> fix: ci for windows cuda builds

- cortex-js/package.json
- cortex-js/src/command.ts
- cortex-js/src/infrastructure/commanders/basic-command.commander.ts
- cortex-js/src/infrastructure/providers/cortex/cortex.module.ts
- cortex-js/src/infrastructure/providers/cortex/cortex.provider.ts
- cortex-js/src/main.ts
- cortex-js/src/usecases/cortex/cortex.usecases.ts
- cortex-js/src/usecases/models/models.usecases.ts
- Add HF model pull
- Add Serve command
- Correct model loading
> chore: add HF model pull and add serve command

- .github/workflows/cortex-cpp-build.yml
Add path for dotnet tool windows code signing step
> Add path for dotnet tool windows code signing step

- .github/pull_request_template.md
- .github/workflows/cortex-cpp-build.yml
replace deprecated ci step and add release drafter
> replace deprecated ci step

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
- upgrade cortex.llamacpp to version 0.1.8. Please refer to https://github.com/janhq/cortex.llamacpp/releases recent changes
> chore: cortex.llamacpp to v0.1.8

- cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts
- Remove model param from `run` command.
> chore: remove parameter for run command

- cortex-js/src/infrastructure/commanders/cortex-command.commander.ts
- Add model pull alias
- Closes #
- Closes #
> chore: add model pull alias

- cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts
> chore: remove log

- cortex-js/src/infrastructure/commanders/prompt-constants.ts
- cortex-js/src/infrastructure/commanders/usecases/models.cli.usecases.ts
- fix llama3 chat template
- Closes #
- Closes #
> fix: add llama3 chat template

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
> chore: cortex.llamacpp to version 0.1.10

- cortex-js/package.json
- cortex-js/src/app.module.ts
- cortex-js/src/command.module.ts
- cortex-js/src/infrastructure/commanders/chat.command.ts
- cortex-js/src/infrastructure/commanders/shortcuts/run.command.ts
- cortex-js/src/infrastructure/commanders/usecases/chat.cli.usecases.ts
- cortex-js/src/infrastructure/commanders/usecases/cli.usecases.module.ts
- cortex-js/src/infrastructure/controllers/messages.controller.ts
- cortex-js/src/infrastructure/entities/message.entity.ts
- cortex-js/src/infrastructure/entities/thread.entity.ts
- cortex-js/src/main.ts
- cortex-js/src/usecases/assistants/assistants.usecases.ts
- cortex-js/src/usecases/messages/messages.usecases.ts
- cortex-js/src/usecases/seed/seed.service.ts
- cortex-js/src/usecases/threads/threads.usecases.ts
> feat: store messages when chat via cli

- cortex-js/src/infrastructure/controllers/assistants.controller.ts
- cortex-js/src/infrastructure/controllers/messages.controller.ts
- cortex-js/src/infrastructure/controllers/models.controller.ts
- cortex-js/src/infrastructure/controllers/threads.controller.ts
- cortex-js/src/infrastructure/interceptors/transform.interceptor.ts
This PR adds a transform interceptor to controllers that return list results compatible with the OpenAI SDK format.
> feat: cortex client sdk compatible

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
- https://github.com/janhq/cortex.llamacpp/releases/tag/v0.1.11
- Closes #
- Closes #
> chore: cortex.llamacpp to version 0.1.11

- cortex-cpp/controllers/server.cc
> fix: get models failed

- .github/workflows/cortex-cpp-build.yml
- cortex-cpp/engines/cortex.llamacpp/engine.cmake
- https://github.com/janhq/cortex.llamacpp/releases/tag/v0.1.12
- Disable run e2e test for macos-latest
- Closes #
- Closes #
> chore: cortex.llamacpp to version 0.1.12

- cortex-js/package.json
> fix: bump update-notifier type version

- cortex-js/src/main.ts
- Remove the "/" from the URL
- Closes #
- Closes #
> api: Remove the "/" from the URL

- cortex-js/package.json
- Fix CI issue with `npm ci`
- Closes #
- Closes #
> fix: CI should not run post install but it does

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
https://github.com/janhq/cortex.llamacpp/releases/tag/v0.1.15
-
- Closes #
- Closes #
> chore: cortex.llamacpp to version 0.1.15

- cortex-js/src/app.module.ts
- cortex-js/src/infrastructure/middlewares/app.logger.middleware.ts
- cortex-js/src/main.ts
Add a logger middleware to output registered requests.
- Closes #
- Closes #
> chore: add request logger

- cortex-js/src/infrastructure/controllers/threads.controller.ts
- cortex-js/src/infrastructure/dtos/threads/delete-message.dto.ts
- cortex-js/src/usecases/threads/threads.usecases.ts
- Add delete, retrieve message api
> feat: add delete message api

- cortex-js/src/domain/abstracts/engine.abstract.ts
- Resolved a critical issue causing CI builds to fail
- Closes #
- Closes #
> fix: build error due to relative import path

- cortex-cpp/controllers/server.cc
- cortex-cpp/controllers/server.h
- cortex-cpp/utils/cortex_utils.h
Issue: https://github.com/janhq/cortex/issues/623
- Closes #
- Closes #
> feat: cortex.onnx

- .github/workflows/nightly-build.yml
Change CI name for nightly
- Closes #
- Closes #
> Change CI name for nightly

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
This PR updates the Update cortex.llamacpp nightly to version 0.1.17-15.06.24
> Update cortex.llamacpp nightly to version 0.1.17-15.06.24

- .github/workflows/nightly.yml
Add check number of assert
- Closes #
- Closes #
> Add check number of assert

- .github/workflows/cortex-js-quality-gate.yml
- Add CI test for cortex js
- Closes #
- Closes #
> Add CI test for cortex js

- cortex-js/src/infrastructure/services/file-manager/file-manager.service.ts
> fix error crash reprot file not exist

- .github/workflows/cortex-cpp-build.yml
- .github/workflows/nightly-build.yml
Fix codesign windows error
- Closes #
- Closes #
> Fix codesign windows error

- cortex-js/src/domain/models/model.event.ts
- cortex-js/src/infrastructure/commanders/test/helpers.command.spec.ts
- cortex-js/src/infrastructure/commanders/test/models.command.spec.ts
- cortex-js/src/infrastructure/controllers/chat.controller.spec.ts
- cortex-js/src/infrastructure/controllers/embeddings.controller.spec.ts
- cortex-js/src/infrastructure/controllers/events.controller.ts
- cortex-js/src/infrastructure/controllers/models.controller.spec.ts
- cortex-js/src/usecases/chat/chat.usecases.spec.ts
- cortex-js/src/usecases/models/models.usecases.spec.ts
- cortex-js/src/usecases/models/models.usecases.ts
> feat: add model event

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
This PR updates the Update cortex.llamacpp nightly to version 0.1.17-19.06.24
> Update cortex.llamacpp nightly to version 0.1.17-19.06.24

- .github/workflows/cortex-build.yml
> fix: change ci runner to address visual sdk issue

- cortex-js/package.json
> fix: remove build target from build script

- .github/workflows/cortex-build.yml
- This PR is to update CI to update cortex's package.json
- Closes #
- Closes #
> fix: update cortex package.json version

- .github/workflows/cortex-build.yml
-Correct tag for cortex binary build
- Closes #
- Closes #
> Correct tag for cortex binary build

- cortex-js/package.json
- Address npm install issue with unstable dependency
- Closes #
- Closes #
> fix: remove patch-package dependency

- cortex-js/README.md
- cortex-js/package.json
- cortex-js/src/infrastructure/commanders/usecases/init.cli.usecases.ts
- cortex-js/src/usecases/cortex/cortex.usecases.ts
> chore: rename npm package cortexso

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
> chore: cortex.llamacpp to v0.1.20

- cortex-js/src/infrastructure/controllers/chat.controller.ts
- Error handling for chat/completions endpoint
- Closes #
- Closes #
> chore: error handling for chat/completions endpoint

- cortex-js/src/usecases/models/models.usecases.ts
> fix: download success event

- README.md
- cortex-js/README.md
- Remove the brew installer
- Closes #
- Closes #
> Remove the brew installer

- README.md
- cortex-js/README.md
- Add brew installer section
- Closes #
- Closes #
> Add brew installer section

- cortex-js/package.json
> chore: resolve dependency to suppress warning

- cortex-js/package.json
- Fix error windows bad param
- Closes #
- Closes #
> Fix error windows bad param

- .github/workflows/cortex-build.yml
- Fix syntax error github workflow
- Closes #
- Closes #
> Fix syntax error github workflow

- .github/workflows/cortex-build.yml
- cortex cpp switch to macos-latest runner
- Closes #
- Closes #
> cortex cpp switch to macos-latest runner

- README.md
- cortex-js/README.md
- Remove the `tap` and `untap` brew installation command
- Closes #
- Closes #
> Remove the tap and untap brew installation command

- cortex-js/src/infrastructure/commanders/ps.command.ts
- correct consumed resource table
- Closes #
- Closes #
> fix: correct consumed resource table

- cortex-cpp/Makefile
- cortex-cpp/cortex-cpp-deps/CMakeLists.txt
> fix: use zlib static

- cortex-js/src/infrastructure/database/sqlite-database.providers.ts
- create sqlite tables
- Closes #
- Closes #
> fix: create sqlite tables

- .github/workflows/cortex-js-openai-coverage.yml
- coverage/endpoint_mapping.json
- Chore test openai api
- Closes #
- Closes #
> Chore test openai api

- cortex-js/src/infrastructure/controllers/events.controller.ts
- Fix legacy download issue with leading and trailing event
- Closes #
- Closes #
> fix: throttle leading and trailing event

- cortex-js/package.json
> chore: lock cortex-cpp dependency version

- cortex-js/package.json
- remove --options max-old-space-size=30720,tls-min-v1.0,expose-gc pkg
- Closes #
- Closes #
> remove --options max-old-space-size=30720,tls-min-v1.0,expose-gc pkg

- cortex-cpp/CMakeLists.txt
- cortex-js/package.json
- cortex-js/src/index.ts
- cortex-js/src/usecases/chat/chat.usecases.ts
- Fixed an issue where cortex-cpp node binding module is broken on Electron build
- Closes #
- Closes #
> fix: electron build

- .github/workflows/cortex-build.yml
- Correct path of file source.changes
- Closes #
- Closes #
> Correct path of file source.changes

- cortex-js/src/usecases/models/models.usecases.ts
- It returns 409 which is unclear
- Closes #
- Closes #
> fix: should not return failed code on model already loaded

- .github/workflows/cortex-build.yml
- Add exe to release for winget
- Closes #
- Closes #
> Add exe to release for winget

- cortex-js/src/infrastructure/commanders/chat.command.ts
- cortex-js/src/infrastructure/commanders/services/chat-client.ts
- cortex-js/src/infrastructure/services/download-manager/download-manager.service.ts
- This is to add inference chat preset support 
- Fixed an issue where models' download progress updated every 4% instead of 1%
- Closes #
- Closes #
> chore: inference chat preset support

- cortex-js/package.json
- cortex-js/src/infrastructure/commanders/models/model-list.command.ts
> chore: add model version output

- cortex-js/package.json
- cortex-js/src/infrastructure/commanders/run.command.ts
- cortex-js/src/infrastructure/commanders/test/models.command.spec.ts
- cortex-js/src/infrastructure/controllers/embeddings.controller.spec.ts
- cortex-js/src/infrastructure/controllers/models.controller.ts
- cortex-js/src/infrastructure/repositories/extensions/extension.repository.ts
- cortex-js/src/usecases/cortex/cortex.usecases.ts
- cortex-js/src/usecases/models/models.usecases.spec.ts
- cortex-js/src/usecases/models/models.usecases.ts
- Incorrect model load log
- Start model from usecase install of controller
- 
- Closes #
- Closes #
> chore: correct output logs

- cortex-cpp/engines/cortex.llamacpp/engine.cmake
> bump cortex llamacpp for lla‌ma 3.1

- .github/workflows/cortex-js-openai-coverage.yml
- Fix openai api pipeline
- Closes #
- Closes #
> Fix openai api pipeline

- cortex-js/src/infrastructure/commanders/types/model-tokenizer.interface.ts
- cortex-js/src/usecases/models/models.usecases.ts
- cortex-js/src/utils/huggingface.ts
- Retrieve context length and ngl from gguf file
- Closes #
- Closes #
> chore: persist context length and ngl from gguf file

- cortex-js/src/infrastructure/services/download-manager/download-manager.service.ts
- delete  local files when aborting the download
- delete local files when download got an error 
- Closes #
- Closes #
> chore: delete local file when abort download

- package-managers-template/launchpad/cortexso/debian/postrm
- package-managers-template/launchpad/cortexso/debian/prerm
- Add launchpad uninstaller prerm and postrm
- Closes #
- Closes #
> Add launchpad uninstaller prerm and postrm

- .github/workflows/cortex-build.yml
- cortex-js/Makefile
- Fix codesign windows
- Closes #
- Closes #
> Fix codesign windows

- cortex-js/src/app.ts
> Update the Base URL for the API reference to reflect the new URL

- .github/workflows/cortex-build.yml
- cortex-js/Makefile
- cortex-js/entitlements.plist
- Fix codesign macos for application and installer
- Closes #
- Closes #
> Fix codesign macos for application and installer

- cortex-js/src/usecases/cortex/cortex.usecases.ts
- Fixed an issue where cortex does not recognize env such as PATH or so after bundled. Thus no cuda detected
- Closes #
- Closes #
> fix: env does not work after bundled in an electron app

- cortex-cpp/controllers/server.cc
- cortex-cpp/controllers/server.h
> feat: support unload engine

- cortex-js/src/usecases/models/models.usecases.ts
- fix checksum undefined
- Closes #
- Closes #
> fix: fix checksum undefined

- cortex-js/package.json
- Chore bump cortex-cpp to 0.5.0-34
- Closes #
- Closes #
> Chore bump cortex-cpp to 0.5.0-34

- cortex-cpp/package.json
- cortex-js/package.json
- Fix brew build from source error
- Closes #
- Closes #
> Fix brew build from source error

- .github/workflows/cortex-build.yml
- Timed out past pipeline
- Closes #
- Closes #
> fix: increase CI timeout

- cortex-js/src/domain/models/resource.interface.ts
- cortex-js/src/infrastructure/services/resources-manager/resources-manager.service.ts
> fix: add used vram into system event body

- cortex-js/src/index.ts
- cortex-js/src/usecases/engines/engines.usecase.ts
> feat: expose server instance
